### ISSUE TITLE
[Feature] 장소 검색 구현

### ISSUE THREAD

**Issue by walwaljj** [OvercomingRoom/ULPET-BE#8]
## 📝 Description

통합 검색을 구현합니다.
동적 쿼리를 위해 queryDsl 을 사용합니다.

## ☑️ TODO

- [x] queryDsl 설정
- [x] 카테고리 검색 구현
- [x] 키워드 검색 구현 (장소 명 또는 주소 검색)
- [X] 특징 검색 구현
